package com.electroshop.electroshop_backend.enums;

public enum Categories {
	
	LAPTOP,
	TABLETS,
	HEADPHONES,
	COMPUTER_ACCESSORIES,
	GAMING_LAPTOP,
	SPEAKERS_SOUNDBARS,
	SMARTWATCHES,
	MUSICAL_INSTRUMENT,
	DESKTOPS,
	MONITORS,
	PRINTER,
	STORAGE,
	NETWORKING,
	CAR_ELECTRONICS,
	COMPONENTS,
	BATTERIES_CHARGERS,
	POWER_ACCESSORIES	
	
}
