spring:
  application:
    name: electroshop-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/electroshop
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  security:
    user:
      name: user
      password: pass
      roles: USER